### ISSUE TITLE
Linux Kernel Problem? Idk

### ISSUE THREAD

**Issue by CarlosNunezMX** [eugeniodepalo/react-native-gtk4#1]
Hello, Sorry for disturbing, I'm trying to start sample app, but I'm reciving so many error and core dumps.

Here one when i do `node dist/index.js`
```
node: src/unix/linux.c:1091: uv__poll_io_uring: Declaration `uv__has_active_reqs(loop)' no se cumple.
Aborted (`core' generated)
```

Im trying with:
 - Arch Linux (6.4.1-arch2-1)
 - Gnome 44
 - Libuv 1.46.0-1
 - NodeJS 20.4.0-1
 - PNPM 8.6.6
 - gtk4 1:4.10.4-1
Thanks for ur attention

**Comment by eugeniodepalo** [comment]
Hi @CarlosNunezMX,
Thanks for the bug report. I’ve started working on this only a few days ago so it might very well be a bug in my code, but have you tried updating to version 1.3.5? I’ve fixed a SIGSEGV.

**Comment by eugeniodepalo** [comment]
Should be fixed by https://github.com/eugeniodepalo/react-native-gtk4/commit/6ae7bda1cf8cdaa2990e3431782fc7cc9a5958a9.

**Comment by eugeniodepalo** [comment]
Not exactly sure why but https://github.com/eugeniodepalo/react-native-gtk4/commit/af5b6e62ee0d24445ef61479b38079f812d792a8 fixes this in my Arch installation.

**Comment by eugeniodepalo** [comment]
Should be fixed by https://github.com/eugeniodepalo/react-native-gtk4/commit/90b349e1c5eb604f0a46220cfb977cb243934480. Let me know if that's not the case for you.

**Comment by eugeniodepalo** [comment]
This is now definitely fixed by https://github.com/eugeniodepalo/react-native-gtk4/commit/858d5e7972f7bc2ca53bd321e021d3a81d52888e.
